linuxdeepin/startdde

misc/Xsession.d/00deepin-dde-env, misc/profile.d/deepin-xdg-dir.sh
set XDG_DATA_DIRS to $HOME/.local/share /usr/local/share /usr/share
Issue: Fixed https://github.com/linuxdeepin/developer-center/issues/2457
Log:
Resolve https://github.com/linuxdeepin/developer-center/issues/1675
=> fix: missing XDG_DATA_DIRS environment variables

debian/changelog, display/manager.go
dwayland通过xsettings获取主屏信息的变化，用于实现wayland下主屏设置功能
确保qt接口和display服务的主屏数据一致
Log: 解决wayland下主屏功能异常问题
Influence: 当主屏发生变化后，及时更新到xsettings
Bug: https://pms.uniontech.com/bug-view-146451.html
=> fix: 当主屏发生变化后，及时更新到xsettings

debian/control
从 debian/control 中移除 gvfs-bin 依赖
gvfs 的使用应该是历史版本 https://github.com/linuxdeepin/startdde/commit/f5b19ce52e03bbce55edd24a08fb5733c2f1254b 所需，目前版本看上去不再包含对 gvfs 的直接调用了（并且 gvfs 已被 gio 取代，前者已被废弃）。此提交移除了对 gvfs-bin 的依赖声明。
这个提交是解决 https://github.com/linuxdeepin/developer-center/issues/3230 问题的一部分。
=> chore: remove gvfs-bin dependency from control file

display/manager.go
wayland 情况下插拔显示器会触发先移除后增加，由于无显示器情况下会出现空
id 的情况导致条件不成立，无法应用配置。
Log: 修复wayland下插拔显示器分辨率与配置不同步问题
Bug: https://pms.uniontech.com/bug-view-149827.html
Influence: 显示
Change-Id: I83fde33fa9a1a25bb2905396daec881d7731dca5
=> fix(display): 修复wayland下插拔显示器分辨率与配置不同步问题

display/manager_ifc.go
单屏下真实显示模式为仅单屏与设置的模式不一致，应维持上次显示模式。
Log: 修复扩展模式开机，副屏桌面未显示问题
Bug: https://pms.uniontech.com/bug-view-154359.html
Influence: 显示
Change-Id: I801d1af7b693de09f14e488d168e756dabd27f81
=> fix(display): 修复单屏下真实显示模式不正确的问题

display/manager.go
问题
多用户配置相互冲突
Log: 修复多屏下切换用户，插拔显示器恢复到上个用户配置显示模式
问题
Bug: https://pms.uniontech.com/bug-view-155839.html
Influence: 显示
Change-Id: I68780295f9d0c231fff03331705ef49a88b278e0
=> fix(display): 修复多屏下切换用户，插拔显示器恢复到上个用户配置显示模式

archlinux/PKGBUILD, display/manager.go
切换显示模式时,设置色温的传参错误,从而恢复为0了,设置显示模式不应该去设置色温调节模式
Log: 修复仅X屏下设置手动调节色温，然后切换仅另一个屏幕显示,再切换过来时，色温会恢复成默认未开启状态
Bug: https://pms.uniontech.com/bug-view-156687.html
Influence: 色温调节
=> fix: 修复仅X屏下设置手动调节色温，然后切换仅另一个屏幕显示,再切换过来时，色温会恢复成默认未开启状态

display/manager.go
handleTouchscreenChanged会调用窗管接口，cgo里面的调用，窗管接口崩溃后导致startdde崩溃 添加该代码Bug：https://pms.uniontech.com/zentao/bug-view-78358.html 去除handleTouchscreenChanged后，未复现上述bug
先使用规避方案处理该bug
窗管崩溃问题，后续采取demo方式跟踪
Log: 移除激活session更新触摸屏配置
Influence: 多账户多屏切换账户
Bug: https://pms.uniontech.com/bug-view-156083.html
Change-Id: I9d8105b3f997825540b81a2dcd8fd1afbfbbbbd1
=> fix: 移除激活session更新触摸屏配置

display/manager.go
分辨率不同的情况下,切换复制模式触发了主屏设置,此时主屏设置在分辨率改变之前,导致大小错误
复制模式下不存在主副屏之分,不应该改变主副屏
Log: 修复不同分辨率下切换复制模式,高亮显示不全的问题
Bug: https://pms.uniontech.com/bug-view-147319.html
Influence: 显示模式
=> fix: 修复不同分辨率下切换复制模式时,高亮显示不全的问题

session.go
2表示鼠标滑轮按下；
4表示鼠标滑轮上滑；
5表示鼠标滑轮下滑；
Log: 对鼠标中键，按下、上滑、下滑均做唤醒显示器处理
Influence: 鼠标滑轮操作唤醒显示器
Bug: https://pms.uniontech.com/bug-view-162365.html
Change-Id: I2ef5b0800a9ca5bcf0bd7dbd05ce73aa06d85271
=> fix: 处理鼠标中键(滑轮)按下唤醒

main.go
Log: 修复 kwin 存在时设置 'wm-cmd' 不生效的问题
Influence: 用户可自定义窗管
Change-Id: I193b7b93312b4d559382cf20441e55b419d87d68
=> fix: make 'wm-cmd' as preferred if non-empty

display/manager.go
由于单屏和复制模式共用配置文件，单屏也是复制模式，导致没有更新主屏
Log: 修复PGV拔掉HDMI线，插上VGA，桌面壁纸显示黑屏的问题
Bug: https://pms.uniontech.com/bug-view-166025.html
Influence: 主屏
=> fix: 修复PGV拔掉HDMI线，插上VGA，桌面壁纸显示黑屏的问题

display/manager.go
登录后默认获取的第一个屏幕作为主屏，由于复制模式下没有重新去设置，主屏未更新
Log: 修复KLV复制模式下注销后登陆，显示外屏的壁纸
Bug: https://pms.uniontech.com/bug-view-166261.html
Influence: 主屏
=> fix: 修复KLV复制模式下注销后登陆，显示外屏的壁纸

display/xorg.go
由于休眠唤醒后没有移除monitor信号,导致会多一个monitor,所以移除原来的判断条件,遍历原有的monitor,移除不存在的
Log: 规避待机会多一个displaylink显示器问题
Bug: https://pms.uniontech.com/bug-view-174637.html
Influence: displaylink
Change-Id: I4de93dba64e442cad59d5c9d04670c78e0886d6e
=> fix: 规避休眠会多一个displaylink显示器问题

display/manager.go
handlePrimaryRectChanged没有对pmi做判空处理导致startdde崩溃
Log: 修复displaylink热插拔导致崩溃问题
Bug: https://pms.uniontech.com/bug-view-176547.html
Influence: displaylink热插拔
Change-Id: I6790aed876a8bdd7b20abd06ac014eb7dff5eb63
=> fix: 增加handlePrimaryRectChanged中pmi的判空处理

display/manager.go, misc/dsettings/org.deepin.Display.json
部分显卡lspci没有VGA compatible controller相关数据，需要特殊处理
Log: 修复X100显卡不显示色温调节项的问题
Bug: https://pms.uniontech.com/bug-view-177571.html
Influence: 色温显示
Change-Id: I58a700046eaff5ef4b2fece3574b8e59dd8035ec
=> fix: 修复X100显卡不显示色温调节项的问题

display/manager.go
显示配置文件出错，设置复制模式之前校验文件数据
Log: 修复扩展模式切换到复制模式失效的问题
Bug: https://pms.uniontech.com/bug-view-180033.html
Influence: 切换显示模式
=> fix: 修复扩展模式切换到复制模式失效的问题

display/manager.go, main.go, session_process.go, sound_effect.go
1. 探测是否支持gamma值设置的逻辑放到协程中处理,drmSupportGamma属性在启动过程中不被需要;
2. 优化启动pulseaudio:因为该逻辑要在播放登录音效和dde-session-daemon的part2之前启动,因此在这两个之前分别使用sync.Once加载;
Log: 优化登录加载速度
Bug: https://pms.uniontech.com/bug-view-178975.html
Change-Id: I3fecc0d09b9ffe67fec79af4afb81ee8b12ccd74
=> perf: 优化登录加载速度

misc/Xsession.d/00deepin-dde-env
玲珑应用会把配置文件安装到 /persistent/... 下
需要配置环境变量让 dde-dconfig-daemon 去相应目录
下遍历 meta 配置文件，否则玲珑应用无法使用 DConfig 功能
Log: dconfig support linglong app
Influecne: linglong app
Bug: https://pms.uniontech.com/bug-view-182341.html
=> feat: 为玲珑应用使用 dconfig 配置环境

debian/control
移除 dde-api-proxy 依赖，不再默认提供 v20 DBus 兼容。
Influence: 所有仍在使用 v20 DDE 相关 DBus 的应用
=> chore: remove dde-api-proxy from dependencies list

debian/control, rpm/startdde.spec
deepin-kwin provides the dde-kwin
=> chore: remove dde-kwin runtime dependencies

session.go
当前应用的自启动改为由AM 管理, 这里的先移除
Log: 修复系统升级成功消息重复弹出的问题
Resolve: https://github.com/linuxdeepin/developer-center/issues/3819
=> fix: 系统升级成功消息重复弹出

display/manager.go, display/xorg.go, wl_display/manager.go
当前启动时会根据分辨率最小的屏幕设置全局缩放，这在某些场景下可能并不是用户想要的，比如用户有个高分屏是主屏幕，还有一个低分屏只用来看点简单的信息，当前的模式就会导致用户的主屏也无法正常以全局缩放模式正常使用。 该PR允许用户编辑`~/.config/deepin/force-scale-factor.ini`为如下内容，强制系统的全局缩放：
```
[ForceScaleFactor]
scale=1.5
```
Log: 允许用户通过 force-scale-factor.ini 强制设置全局缩放
=> feat: 允许用户通过 force-scale-factor.ini 强制设置全局缩放

Makefile
=> fix: Makefile中systemd target wants链接到构建临时目录

startmanager.go
not try to newSettings without dde-launcher schema installed
log: as title
=> startdde get into trap without dde-launcher installed

main.go
play login sound has been implement in dde-session, so startdde not need to do that
Log:
=> chore: clean redundance code

display/color_temp.go, display/display.go, display/displayconf.go
插件设置护眼模式开关，控制中心色温做联动；
本地保存色温开启时的配置，以供护眼模式使能时恢复配置
=> feat: 支持插件设置护眼模式

display/color_temp.go, display/display.go, display/exported_methods_auto.go, display/manager.go, display/manager_ifc.go, misc/dsettings/org.deepin.Display.json
色温调节支持用户自定义
Log: 色温调节支持用户自定义
pms: TASK-369021
=> feat: 色温调节支持用户自定义
