linuxdeepin/startdde

- session.go
- xcursor/xcursor.go
Change-Id: I10838c85cfb7e8ab5767a30913c5b07d96c78170
> fix: root window cursor is not left_ptr when use kwin as wm

- session.go
Fixes https://github.com/linuxdeepin/developer-center/issues/931
> fix: bamfdaemon.service start request repeated too quickly

- display/manager_ifc.go
https://github.com/linuxdeepin/internal-discussion/issues/1199
> fix(display): rotate the screen for the first time, then reset, but failed

- xsettings/scale.go
in the file qt-theme.ini if there is only one monitor
> feat: set screenScaleFactors to a number

- xsettings/scale.go
when not modify plymouth theme
https://github.com/linuxdeepin/internal-discussion/issues/1305
> fix: not send SetScaleFactorDone signal

- session.go
- wm_kwin/wm_kwin.go
https://github.com/linuxdeepin/internal-discussion/issues/1357
> fix: kwin is not affected by the choice of dde-wm-chooser

- wm_kwin/wm_kwin.go
- xsettings/xsettings_dpi.go
https://github.com/linuxdeepin/internal-discussion/issues/1373
> chore(xsettings): do not set Xft.dpi in RESOURCE_MANAGER 

- session.go
- xsettings/scale.go
> chore: do not set DEEPIN_WINE_SCALE in ~/.dde_env

- display/manager.go
- display/monitor.go
- display/stup.go
https://github.com/linuxdeepin/internal-discussion/issues/1673
> fix(display): monitor path is invalid

- xsettings/xsettings_writer.go
Change-Id: I35b1605e821fc599ab207a6ebabd41361ed88d91
> fix(xsettings): make last change series auto increment

- xsettings/xsettings.go
Change-Id: I6df42d0112dd9f6257d05d44a9560d6d74ea439d
> fix(xsettings): make serial auto increment in header

- main.go
- session.go
change api
https://github.com/linuxdeepin/internal-discussion/issues/943
> feat: support loginctl lock/unlock-session

- session.go
Change-Id: I8460d15da869f45f8ed3a8175dbd0446461638b8
> feat: set dpms off before reboot/shutdown

- session.go
Change-Id: I7aa1b12d8f860191fbf0e91d797f954c936e0488
> feat: black screen when suspend/hibernate

- session.go
Change-Id: I1987fb0f52c2df771046758bb4accd4d604183b1
> fix: change the dpms off order

- misc/Xsession.d/00deepin-dde-env
QT_LOGGING_RULES influence qt dev on deepin,
now unset QT_LOGGING_RULES on deepin
Log: unset QT_LOGGING_RULES on deepin
> fix: unset QT_LOGGING_RULES on deepin

- misc/Xsession.d/01deepin-profile
source $HOME/.profile
fix [linuxdeepin/developer-center#2368](https://github.com/linuxdeepin/developer-center/issues/2368)
Log: source $HOME/.profile
> fix: source $HOME/.profile

- display/manager.go
- display/manager_test.go
如果是摩尔显卡，需要显示色温调节模块
Task: https://pms.uniontech.com/task-view-174025.html
Influence: 色温调节模块
Change-Id: Iccbea31c54cd8138bb52beb904fff0bf93057396
> feat: 适配色温调解模块显示逻辑

- display/brightness/brightness.go
ddcci优化, 调用helper接口检查是否支持ddcci
Log: ddcci优化, 调用helper接口检查是否支持ddcci
Bug: https://pms.uniontech.com/bug-view-155827.html
Influence: backlight-helper
> feat: ddcci优化, 调用helper接口检查是否支持ddcci

- README.md
- README.zh_CN.md
- debian/startdde.1
The protocol name in the README is written according to the standard specification
Log: modify README license information
Influence: none
Task: https://pms.uniontech.com/task-view-185215.html
Change-Id: If447e2fad5089ebe2dd203193aac023941cc6238
> chore: modify README license information

- debian/deepin-fix-xauthority-perm.1
The protocol name in the  .1 file is written according to the standard specification
Log: modify .1 file license information
Influence: none
Task: https://pms.uniontech.com/task-view-185215.html
Change-Id: Id498cb5396e35ba8ebdab89b464693d1891ea4cf
> chore: modify .1 file license information

- session.go
com.deepin.api.XEventMonitor ButtonPress和ButtonRelease 在移动鼠标中键的时候会有信号发送
在startdde中响应该信号唤醒屏幕
Log: 响应鼠标中键事件，打开屏幕
Influence: 鼠标中键唤醒显示器
Bug: https://pms.uniontech.com/bug-view-162365.html
Change-Id: Ia840a64a6779d8ca8dd8996db70347a8dc824859
> fix: 响应鼠标中键事件，执行打开屏幕命令

- misc/po/de.po
- misc/po/en_US.po
- misc/po/fr.po
- misc/po/it.po
- misc/po/pl.po
- misc/po/pt.po
- misc/po/pt_BR.po
- misc/po/ru.po
更新翻译
Log: 更新翻译
Task: https://pms.uniontech.com/task-view-202015.html
Influence: 通知提示
Change-Id: I8c1c5d32c896cae9c153681185d549e8bb48a24f
> chore: 更新翻译

- session.go
上个版本只处理了鼠标下滑
Log: 鼠标中键上下滑动均能响应唤醒
Influence: 鼠标滑动唤醒显示器
Bug: https://pms.uniontech.com/bug-view-162365.html
Change-Id: Ice0c03e8b08be7c80d8b18fb1383c1e8e108c734
> fix: 处理鼠标中键上滑

- misc/schemas/com.deepin.dde.display.gschema.xml
删除配置文件中的工号
Log: 删除配置文件中的工号
Task: https://pms.uniontech.com/task-view-209113.html
Influence: 无
> fix: 删除配置文件中的工号

- display/xorg.go
usb手写屏接入时，会新增monitor，需要增加对该monitor的处理
Log: 修复usb手写屏热插拔不生效问题
Bug: https://pms.uniontech.com/bug-view-135213.html
Influence: 显示设备热插拔
Change-Id: Ifab669a06e5ea9afb3cbf12d17ab1df9b70d70e9
> fix: 修复usb手写屏热插拔不生效问题

- display/manager.go
- xsettings/xsettings_info.go
主屏数据错误导致任务栏显示出错
Log: 修复主屏数据错误的问题
Influence: 任务栏显示到错误的主屏
Bug: https://pms.uniontech.com/bug-view-161077.html
Change-Id: Icd6e1e295c523c93e1ae59f31727d5657e5354c7
> fix: 修复主屏数据错误的问题

- archlinux/PKGBUILD
- debian/control
- display/brightness.go
- display/brightness/brightness.go
- display/display.go
- display/manager.go
- misc/dsettings/org.deepin.Display.json
新增dconfig配置,用于厂商定制内容合并主线
Log: 新增dconfig配置,用于厂商定制内容合并主线
Task: https://pms.uniontech.com/task-view-220857.html
Influence: 厂商适配
Change-Id: Ief73adcecf97643d8137bce6e758d6740581ef09
> feat: 新增dconfig配置,用于厂商定制内容合并主线

- .tx/deepin.conf
- debian/changelog
update changelog to 5.9.63
Log: update changelog to 5.9.63
Change-Id: Ic9989f296ce229cfe2e6627c8f1119d771db6f9e
> chore: update changelog to 5.9.63

- xsettings/xsettings_info.go
添加滚动条显示策略配置项gsetting和xsetting转换
Log: 个性化增加滚动条设置
Task: https://pms.uniontech.com/task-view-212919.html
Influence: 个性化增加滚动条设置
> feat: 个性化增加滚动条设置

- .tx/deepin.conf
- debian/changelog
update changelog to 5.10.2
Log: update changelog to 5.10.2
Influence: 构建
Change-Id: I923176ad0471e847ce22167aa2106261f67ccfbd
> chore: update changelog to 5.10.2

- display/manager.go
修改DMIInfo数据获取方式为异步
Log: 修改DMIInfo数据获取方式为异步
Bug: https://pms.uniontech.com/bug-view-183185.html
Influence: startdde启动
Change-Id: I025add89b51c33074dc0ec4f67d0f3fbcbb8ad6e
> fix: 修改DMIInfo数据获取方式为异步

- xsettings/xsettings_info.go
增加界面模式配置项的xsetting和gsetting转换
Log: 个性化提供界面模式设置
Task: https://pms.uniontech.com/task-view-212923.html
Influence: 个性化提供界面模式设置
> feat: 个性化提供界面模式设置

- debian/control
- misc/auto_launch/chinese.json
- misc/auto_launch/default.json
remove auto launch
remove unit test
> chore: remove deepin-turbo depend

- misc/Xsession.d/00deepin-dde-env
- Re-apply https://github.com/linuxdeepin/startdde/pull/104
- A cherry-pick patch of https://github.com/linuxdeepin/startdde/commit/802525466d72f398f23e91b10963ca46a9f01b79
> fix: unset QT_LOGGING_RULES on deepin (#104)

- debian/control
dde-session provide wayland session entry
> chore: remove dde-wayland-config

- session.go
> fix: 关机音效存在杂音

- debian/control
- display/wayland.go
- go.mod
- go.sum
- launch_group.go
- memchecker/config.go
- session.go
- startmanager.go
- wl_display/kwayland_dbus.go
Log: search config file in xdg dir
> feat: search config file in xdg dir

- misc/Xsession.d/94qt_env
some platform not install dde wayland backend(kwayland-shell). the Qt program cannot startup.
https://bbs.deepin.org/post/260843?id=260843
> chore: add multi qt wayland backends

- debian/changelog
发布 startdde ~~6.0.9.1~~ 6.0.10
Log:
> chore: release startdde 6.0.10

- debian/changelog
> chore: release startdde 6.0.11

- debian/changelog
> chore: release 6.0.12

- .gitignore
- main.go
dde-daemon has been proxy setup, so remove this from startdde
Log:
> fix: export proxy env error

- Makefile
- misc/systemd_task/dde-display-task-refresh-brightness.service
> fix: dde-display-service not started

- debian/changelog
> chore: release startdde 6.0.13

- debian/changelog
- xsettings/scale.go
Log: fix issue https://github.com/linuxdeepin/developer-center/issues/7039
> fix: also set cursorSize for deepin-kwin

- archlinux/PKGBUILD
> chore: fix archlinux build

- display/color_temp.go
- display/manager.go
使用专业版方案，使用redshift传入经纬度调节色温。
Issue: https://github.com/linuxdeepin/developer-center/issues/10453
> chore: 解决色温没有自动调节的问题

- xsettings/xsettings_info.go
紧凑模式需要设置DTK/SizeMode
Task: https://pms.uniontech.com/task-view-362569.html
> chore: 紧凑模式需要设置DTK/SizeMode

- debian/changelog
release 6.0.18
Log: bump version to 6.0.18
> chore: bump version to 6.0.18

- xsettings/xsettings_info.go
add config
Log:
Task: https://pms.uniontech.com/task-view-364175.html
> feat: add qt-scrollbar-policy config

- xsettings/xsettings_info.go
add the setting that represents the active color in dark theme
Log:
> chore: add the QtActiveColorDark setting

- xsettings/xsettings_info.go
rename "Qt/ActiveColorDark" to "Qt/DarkActiveColor"
Log:
> chore: rename "Qt/ActiveColorDark" to "Qt/DarkActiveColor"

- debian/changelog
release 6.0.19
Log: bump version to 6.0.19
> chore: bump version to 6.0.19

- debian/changelog
> chore: bump version to 6.1.0

- debian/changelog
> chore: bump version to 6.1.1

- display/color_temp.go
- display/config.go
- display/config_v3_3.go
- display/config_v4.go
- display/manager.go
- display/util.go
- wl_display/config.go
- wl_display/config_v3_3.go
- wl_display/manager.go
- wl_display/util.go
- xsettings/xsettings_dpi.go
- xsettings/xsettings_test.go
> chore: remove deprecated ioutil

- misc/dsettings/org.deepin.XSettings.json
缩放不为0时,采用了配置的缩放
Log:
pms: TASK-371809
> fix: 修复第一次安装系统，高分辨屏幕缩放错误

- misc/schemas/com.deepin.dde.display.gschema.xml
默认配置出错
Log: 修复首次外接双屏，默认应该为扩展模式
pms: BUG-292951
> fix: 修复首次外接双屏，默认应该为扩展模式

- debian/control
去掉qt5相关依赖
Log: 去掉qt5相关依赖
pms: TASK-369021
> feat: 去掉qt5相关依赖
